name: ✨ Feature request
description: Propose a new capability
title: "[FEAT] <short title>"
labels: ["type: feature", "needs triage"]
body:
  - type: textarea
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
