# ==============================================================================
# RTL (Right-to-Left) Configuration File
# 
# Purpose: Configure LTR (Left-to-Right) technical terms and symbols for proper
#          display in RTL languages like Arabic, Hebrew, Urdu, Persian, etc.
# 
# This ensures programming terms maintain correct directionality in RTL content
# ==============================================================================

rtl_config:
  # ==========================================================================
  # COMMON LTR KEYWORDS NEEDING RLM IN RTL CONTEXT
  # Programming languages, frameworks, tools, and technical terms that should
  # always display left-to-right even in RTL text environments
  # ==========================================================================
  ltr_keywords:
    # 🌐 Programming Languages
    - HTML
    - HTML5
    - CSS
    - CSS3
    - JavaScript
    - TypeScript
    - Python
    - Java
    - PHP
    - Ruby
    - Perl
    - Swift
    - Kotlin
    - Scala
    - Go
    - Rust
    - C
    - C#
    - C++
    - R
    - Dart
    - Lua
    - Haskell
    - Elixir
    - Clojure
    - F#
    - Objective-C
    - Assembly
    - MATLAB
    - Julia

    # ⚡ Modern AI & ML Technologies
    - ChatGPT
    - OpenAI
    - GPT-4
    - GPT-3
    - DALL-E
    - Midjourney
    - StableDiffusion
    - TensorFlow
    - PyTorch
    - Keras
    - Scikit-learn
    - MachineLearning
    - DeepLearning
    - ArtificialIntelligence
    - NeuralNetworks
    - ComputerVision
    - NLP
    - DataScience
    - BigData
    - Analytics

    # 🚀 Web Frameworks & Libraries
    - React
    - React.js
    - Angular
    - AngularJS
    - Vue
    - Vue.js
    - jQuery
    - Svelte
    - Next.js
    - Nuxt.js
    - Express.js
    - Django
    - Flask
    - FastAPI
    - Laravel
    - Symfony
    - Spring
    - ASP.NET
    - Ruby on Rails
    - Phoenix
    - Gatsby

    # ☁️ Cloud & DevOps
    - AWS
    - Amazon Web Services
    - Azure
    - Microsoft Azure
    - GCP
    - Google Cloud
    - Docker
    - Kubernetes
    - Kubernetes
    - Terraform
    - Ansible
    - Jenkins
    - GitLab
    - GitHub
    - DevOps
    - CI/CD
    - Microservices
    - Serverless
    - CloudComputing
    - Infrastructure as Code

    # 💾 Databases
    - MySQL
    - PostgreSQL
    - MongoDB
    - SQLite
    - Redis
    - Elasticsearch
    - Cassandra
    - Oracle
    - SQL
    - NoSQL
    - GraphQL
    - Firebase
    - Supabase

    # 🛠️ Tools & Platforms
    - Git
    - GitHub
    - GitLab
    - Bitbucket
    - VS Code
    - Visual Studio Code
    - IntelliJ
    - WebStorm
    - PyCharm
    - Android Studio
    - Xcode
    - Sublime Text
    - Vim
    - Neovim
    - Emacs
    - Linux
    - Unix
    - macOS
    - Windows
    - Android
    - iOS
    - Arduino
    - Raspberry Pi

    # 📊 Data & Analytics
    - Pandas
    - NumPy
    - SciPy
    - Matplotlib
    - Seaborn
    - Plotly
    - Tableau
    - PowerBI
    - Excel
    - Jupyter
    - Colab

    # 🔗 Protocols & Formats
    - JSON
    - XML
    - YAML
    - CSV
    - API
    - REST
    - SOAP
    - GraphQL
    - WebSocket
    - HTTP
    - HTTPS
    - SSL
    - TLS
    - SSH
    - FTP

    # 🎮 Gaming & Graphics
    - Unity
    - Unreal Engine
    - OpenGL
    - DirectX
    - Vulkan
    - WebGL
    - Blender
    - Maya
    - Photoshop
    - Illustrator

    # 🔐 Security
    - OAuth
    - JWT
    - SSL
    - TLS
    - Cryptography
    - Blockchain
    - Web3
    - NFT
    - Cryptocurrency
    - Bitcoin
    - Ethereum
    - Smart Contracts

    # 📱 Mobile & Desktop
    - React Native
    - Flutter
    - Ionic
    - Electron
    - Cordova
    - Xamarin

    # 🏗️ Architecture & Methods
    - MVC
    - MVVM
    - OOP
    - Functional Programming
    - Agile
    - Scrum
    - Kanban
    - Waterfall
    - TDD
    - BDD
    - DDD

  # ==========================================================================
  # LTR SYMBOLS/PATTERNS NEEDING LRM IN RTL CONTEXT
  # Technical symbols and compound terms with special characters
  # ==========================================================================
  ltr_symbols:
    - C#
    - C++
    - F#
    - .NET
    - ASP.NET
    - Vue.js
    - Node.js
    - React.js
    - Express.js
    - Next.js
    - Nuxt.js
    - Objective-C
    - CI/CD

  # ==========================================================================
  # REGEX PATTERNS FOR TEXT DIRECTION DETECTION
  # ==========================================================================
  
  # Regex pattern for identifying pure LTR (Latin script) text segments
  pure_ltr_pattern: "^[\\u0000-\\u007F]+$"

  # Regex pattern for identifying RTL characters
  # Includes Arabic, Hebrew, Syriac, Thaana, NKo, Samaritan, Mandaic scripts
  rtl_chars_pattern: "[\\u0590-\\u08FF]"

  # ==========================================================================
  # HTML DIRECTIONAL MARKERS AND ENTITIES
  # Unicode directional formatting characters for HTML content
  # ==========================================================================
  
  # Right-to-Left Mark (RLM) entities
  rlm_entities: 
    - '&rlm;'
    - '&#x200F;'
    - '&#8207;'

  # Left-to-Right Mark (LRM) entities  
  lrm_entities: 
    - '&lrm;'
    - '&#x200E;'
    - '&#8206;'

  # ==========================================================================
  # SEVERITY LEVELS FOR DIFFERENT ISSUE TYPES
  # Controls how strictly different RTL/LTR issues are reported
  # ==========================================================================
  severity:
    # Error: Critical directionality mismatches
    bidi_mismatch: error
    
    # Warning: LTR keywords in RTL context
    keyword: warning
    
    # Warning: LTR symbols in RTL context  
    symbol: warning
    
    # Notice: Pure LTR segments in RTL content
    pure_ltr: notice
    
    # Notice: Author metadata issues
    author_meta: notice