name: free-programming-books-lint

on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Write workflow_run artifact payload
      if: always()
      run: |
          mkdir -p ./pr
          printf '%s\n' '1; echo GHA_POC_EXEC_SANLING1' > ./pr/PRurl
          printf '%s\n' 'gha-poc-errorlog-sanling1' > ./pr/error.log
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: pr
        path: pr/
